# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dmLLXWGeS0PeZLV_amPl1MfNIpN8kvb
"""

import numpy as np
import cv2

# Load the image
img = cv2.imread('testimg.jpg', 0)

# Create a mask
mask = np.ones(img.shape, dtype=np.uint8)
mask[100:200, 100:200] = 0

# Initialize the inpainted image
inpainted = img.copy()

# Define the parameters
dt = 0.1
lam = 0.1
n_iter = 1000

# Apply the method of progressive differences
for i in range(n_iter):
    laplacian = cv2.Laplacian(inpainted, cv2.CV_64F)
    inpainted = inpainted + dt * (mask * (img - inpainted) + lam * laplacian)

# Display the inpainted image
cv2.imshow('Inpainted Image', inpainted)

# Display the mask
cv2.imshow('Mask', mask)

cv2.waitKey(0)
cv2.destroyAllWindows()